# SPDX-FileCopyrightText: 2026 Venkata Sai Manikanta Yatam
# SPDX-License-Identifier: BUSL-1.1
"""Deterministic double-entry ledger core.

This package is deliberately pure: no I/O, no network, no clock, no randomness.
Every effect the engine needs is injected as a Protocol (``Clock``, ``IdGenerator``,
``FxRateSource``) so that a replay of the same command sequence produces an equal ledger
with identical digests. ``scripts/check_determinism.py`` enforces the ban in CI; see
``docs/adr/0001-architecture.md`` for the reasoning.

The public surface is what this module exports. Submodules are importable but their
layout is not a compatibility promise.
"""

from __future__ import annotations

from ledgergate.ledger.accounts import Account, AccountType, ChartOfAccounts, Side
from ledgergate.ledger.effects import (
    EPOCH,
    Clock,
    FixedClock,
    FxRateSource,
    IdGenerator,
    SequentialIds,
    StaticRates,
    SteppingClock,
)
from ledgergate.ledger.entries import (
    GENESIS_HASH,
    Entry,
    EntryDraft,
    Posting,
    credit,
    debit,
    net_by_currency,
)
from ledgergate.ledger.errors import (
    AccountCurrencyMismatchError,
    AccountError,
    AlreadyReversedError,
    ChainIntegrityError,
    CurrencyMismatchError,
    DuplicateAccountError,
    DuplicateEntryIdError,
    DuplicateTransactionError,
    EmptyEntryError,
    EntryAmountMismatchError,
    EntryError,
    EntryNotAllowedError,
    EntryRequiredError,
    IdempotencyConflictError,
    IllegalTransitionError,
    InsufficientFundsError,
    InvalidAmountError,
    InvalidIdentifierError,
    LedgerError,
    MissingRateError,
    MoneyError,
    RefundExceedsSettledError,
    TransactionError,
    UnbalancedEntryError,
    UnknownAccountError,
    UnknownEntryError,
    UnknownTransactionError,
)
from ledgergate.ledger.fx import Conversion, conversion_entry, price
from ledgergate.ledger.lifecycle import (
    MONETARY_EVENTS,
    TERMINAL,
    TRANSITIONS,
    Transaction,
    TransactionEvent,
    TransactionStatus,
    allowed_events,
    transition,
)
from ledgergate.ledger.money import (
    CHF,
    CURRENCIES,
    EUR,
    GBP,
    INR,
    JPY,
    KWD,
    USD,
    Currency,
    Money,
    RoundingMode,
    currency,
    round_fraction,
    total,
)
from ledgergate.ledger.state import (
    Advance,
    Applied,
    Command,
    Ledger,
    OpenTransaction,
    OperationRecord,
    Post,
    Refund,
    Reverse,
    TrialBalance,
    TrialBalanceRow,
    replay,
)

__all__ = [
    "CHF",
    "CURRENCIES",
    "EPOCH",
    "EUR",
    "GBP",
    "GENESIS_HASH",
    "INR",
    "JPY",
    "KWD",
    "MONETARY_EVENTS",
    "TERMINAL",
    "TRANSITIONS",
    "USD",
    "Account",
    "AccountCurrencyMismatchError",
    "AccountError",
    "AccountType",
    "Advance",
    "AlreadyReversedError",
    "Applied",
    "ChainIntegrityError",
    "ChartOfAccounts",
    "Clock",
    "Command",
    "Conversion",
    "Currency",
    "CurrencyMismatchError",
    "DuplicateAccountError",
    "DuplicateEntryIdError",
    "DuplicateTransactionError",
    "EmptyEntryError",
    "Entry",
    "EntryAmountMismatchError",
    "EntryDraft",
    "EntryError",
    "EntryNotAllowedError",
    "EntryRequiredError",
    "FixedClock",
    "FxRateSource",
    "IdGenerator",
    "IdempotencyConflictError",
    "IllegalTransitionError",
    "InsufficientFundsError",
    "InvalidAmountError",
    "InvalidIdentifierError",
    "Ledger",
    "LedgerError",
    "MissingRateError",
    "Money",
    "MoneyError",
    "OpenTransaction",
    "OperationRecord",
    "Post",
    "Posting",
    "Refund",
    "RefundExceedsSettledError",
    "Reverse",
    "RoundingMode",
    "SequentialIds",
    "Side",
    "StaticRates",
    "SteppingClock",
    "Transaction",
    "TransactionError",
    "TransactionEvent",
    "TransactionStatus",
    "TrialBalance",
    "TrialBalanceRow",
    "UnbalancedEntryError",
    "UnknownAccountError",
    "UnknownEntryError",
    "UnknownTransactionError",
    "allowed_events",
    "conversion_entry",
    "credit",
    "currency",
    "debit",
    "net_by_currency",
    "price",
    "replay",
    "round_fraction",
    "total",
    "transition",
]
